### ISSUE TITLE
如何读取txt类型namespace

### ISSUE THREAD

**Issue by mushramb0** [ctripcorp/apollo.net#107]
请问如果namespace是txt类型,我想单纯读取整个文本,该用什么方法实现呢

**Comment by pengweiqhca** [comment]
目前不支持，建议使用默认格式

**Comment by mushramb0** [comment]
那请问源码哪里限制了 我去看看

**Comment by pengweiqhca** [comment]
不是有什么限制，而是目前不知道怎么解析，你如果想解决可以使用如下方式：
1. 实现IConfigAdapter接口
2. 调用 ConfigAdapterRegister.AddAdapter()，将自己注入进去
