### ISSUE TITLE
部署的Apollo是多环境，如何获取不同环境的配置

### ISSUE THREAD

**Issue by wangcheng0509** [ctripcorp/apollo.net#108]
如题

**Comment by pengweiqhca** [comment]
1. 使用环境变量
2. 使用appsettings.{Environment}.json文件
具体请查看[ASP.NET Core 中的配置](https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/)

**Comment by wangcheng0509** [comment]
![image](https://user-images.githubusercontent.com/34881771/72678140-00469d80-3ade-11ea-89ac-a0029b636f01.png)
我目前能获取到的是DEV配置，的意思是如果

**Comment by wangcheng0509** [comment]
![image](https://user-images.githubusercontent.com/34881771/72678185-81059980-3ade-11ea-92cc-5242f5eaa3ca.png)

**Comment by pengweiqhca** [comment]
apollo不同环境的不同的MetaServer不一样啊

**Comment by wangcheng0509** [comment]
刚问了OP同学，确实，受教了
