### ISSUE TITLE
在framework 下加载多个命名空间下的获取配置信息网络请求超时

### ISSUE THREAD

**Issue by gm0915** [ctripcorp/apollo.net#109]
在framework 下加载多个命名空间时，会出现获取配置信息的网络请求超时，导致c盘配置文件无法创建，配置变更后也无法及时收到通知。

**Comment by pengweiqhca** [comment]
framework默认每个域名两个并发连接，apollo使用长连接。
参考[此处](https://docs.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings)修改

**Comment by gm0915** [comment]
修改配置后可以了，以前没有想到是这个地方的限制，非常感谢 @pengweiqhca
