### ISSUE TITLE
.Net Web API 4.71 下 IConfiguration[key] 不能获取最新配置内容

### ISSUE THREAD

**Issue by szg** [ctripcorp/apollo.net#110]
![image](https://user-images.githubusercontent.com/7257911/79294113-f9c29900-7f07-11ea-857f-ca1eb9cd8cc5.png)
如图，将 key aaa 从 aoaoao... 更新 为 aoao 后，
Configuration[key].value:aoaoao....,AppSetting[key].value:aoao
Global 配置如下
public class WebApiApplication : System.Web.HttpApplication
    {
        public static IConfiguration Configuration { get; private set; }
        protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);

            Configuration = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
              .AddApollo(ConfigurationManager.AppSettings["Apollo.AppId"], ConfigurationManager.AppSettings["Apollo.MetaServer"])
              .AddDefault()
              .Build();
        }
    }
Web.config 配置如下

`<configSections>
    <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  </configSections>
  <configBuilders>
    <builders>
      <add name="AppSettingsSectionBuilder" type="Com.Ctrip.Framework.Apollo.AppSettingsSectionBuilder, Com.Ctrip.Framework.Apollo.ConfigurationManager" />
      <add name="ConnectionStringsSectionBuilder" type="Com.Ctrip.Framework.Apollo.ConnectionStringsSectionBuilder, Com.Ctrip.Framework.Apollo.ConfigurationManager" />
    </builders>
  </configBuilders>
  <connectionStrings configBuilders="ConnectionStringsSectionBuilder" />
  <appSettings configBuilders="AppSettingsSectionBuilder">
    <add key="Apollo.AppId" value="sunnytest" />
    <add key="Apollo.Timeout" value="5000" />
    <add key="Apollo.RefreshInterval" value="3000" />
    <add key="Apollo.Env" value="Dev" />
    <add key="Apollo.MetaServer" value="http://192.168.5.133:8080/" />
    <add key="Apollo.ConfigServer" value="http://192.168.5.133:8080/" />
  </appSettings>`
获取代码如下
        [HttpGet]
        [Route("api/Apollo/Section/{key}")]
        public async Task<string> Section(string key)
        {
            var config = WebApiApplication.Configuration;

            //await ApolloConfigurationManager.GetAppConfig();

            if (string.IsNullOrEmpty(key))
                return await Task.FromResult<string>(null);
            var value = config[key];
            var value2 = ConfigurationManager.AppSettings[key];

            return await Task.FromResult($"{nameof(key)}:{key},Configuration[key].value:{value},AppSetting[key].value:{value2}");
        }

**Comment by szg** [comment]
我用 106.54.227.205:8080 测试的就可以，本地Docker 里边 的就不行。

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-如何跳过meta-service的服务发现

**Comment by szg** [comment]
> [https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-如何跳过meta-service的服务发现](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)

跳过服务发现都是配置过的，也能获取到配置。只是用 ConfigurationManager.AppSettings[key] 能获取到最新的值，但是用IConfiguration[key]获取不到最新值，

**Comment by pengweiqhca** [comment]
你可以运行[Apollo.AspNet.Demo](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.AspNet.Demo/Startup.cs#L23)

**Comment by szg** [comment]
运行之后结果跟我之前发的一致，都是IConfiguration[key]获取不到最新的

**Comment by szg** [comment]
我 部署方式，按照 https://github.com/ctripcorp/apollo/wiki/Apollo-Quick-Start-Docker%E9%83%A8%E7%BD%B2  一、二，执行。跳过服务发现，appsetting 配置
    <add key="Apollo.MetaServer" value="http://192.168.5.133:8080/" />
    <add key="Apollo.ConfigServer" value="http://192.168.5.133:8080/" />

**Comment by pengweiqhca** [comment]
你开启日志看看
``` C#
Com.Ctrip.Framework.Apollo.Logging.UseConsoleLogging()
```

**Comment by szg** [comment]
控制台 程序 没问题的。只有 web下才有这个问题。不太清除原因。但是连接  106.54.227.205:8080 ，也没有配置服务发现 却没有问题。

**Comment by pengweiqhca** [comment]
看看你是这个[问题](https://github.com/ctripcorp/apollo.net/issues/109)吗？

**Comment by szg** [comment]
这个刚也试了，但是我不是这个问题。代码我传 gitee 了，只有 10行代码，希望指正

**Comment by pengweiqhca** [comment]
你的web.config的runtime没有配置正确，请保证编译输出里没有版本重定向输出

**Comment by szg** [comment]
应该跟这个关系不大吧。json.net  引用版本 apollo.net为 6.0.8，现在随便建个 4.5 项目都是10.0+了，对吧，我用 官网 [https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.AspNet.Demo/Startup.cs#L23](Apollo.AspNet.Demo) 运行我本地 docker apollo 结果跟我 4.7.1 有版本重定向一致，我认为，如果不是 代码的问题的话。可能是 docker 部署的问题，因为，我用你们提供的那个地址 106.54.227.205:8080，IConfiguration[key]，AppSetting[key]能得到相同的结果。

**Comment by szg** [comment]
我关掉了
