### ISSUE TITLE
建议加上apollo 1.6+的秘钥通讯功能

### ISSUE THREAD

**Issue by wsjun2016** [ctripcorp/apollo.net#111]
建议在Apollo\Util\Http\HttpUtil.cs文件的Task<HttpResponse<T>> DoGetAsync<T>(string url, int timeout)方法中加上签名的功能，或者扩展出增加Request Header的选项吧

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#42-apollo内部httpclient如何配置代理

**Comment by gmbzero** [comment]
> 建议在Apollo\Util\Http\HttpUtil.cs文件的Task<HttpResponse> DoGetAsync(string url, int timeout)方法中加上签名的功能，或者扩展出增加Request Header的选项吧

查看 Pull requests，我提交了一个支持访问密钥的分支合并请求！

**Comment by burningg** [comment]
强烈建议

**Comment by pengweiqhca** [comment]
@wsjun2016 @burningg 已发新包
