### ISSUE TITLE
.net如何实现热发布

### ISSUE THREAD

**Issue by burningg** [ctripcorp/apollo.net#114]
不太清楚.net如何使用热发布的功能

**Comment by pengweiqhca** [comment]
https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#custom-configuration-provider

**Comment by burningg** [comment]
apollo的热发布功能也是这么使用的么

**Comment by pengweiqhca** [comment]
就是这么简单
