### ISSUE TITLE
.net 客户端，AddNameSpace导致TCP链接过多，阿波罗服务器资源耗尽！

### ISSUE THREAD

**Issue by zhouruizr** [ctripcorp/apollo.net#120]
1、我们公司因为命名空间比较多，所以用了AddNameSpace方法，然后发现每次都会触发StartLongPolling方法建立长连接，每台服务器常年保持TCP链接数在1.2万，多了以后会导致阿波罗资源耗尽，
2、java客户端RemoteConfigLongPollService用的是单例，但是在.net客户端中每次都new 一个。
麻烦大佬看看是否真的有问题，能否优化~

**Comment by zhouruizr** [comment]
![QQ图片20200629171042](https://user-images.githubusercontent.com/25045462/86117692-0ebfc900-bb02-11ea-86f4-f03856c65d2c.png)

**Comment by pengweiqhca** [comment]
一个namespace一个长连接，这个少不了啊

**Comment by zhouruizr** [comment]
但是我看java客户端你说了，一但启动了StartLongPolling任务就不再启动了，多个命名空间时可以放到notifications集合中的吧，ConfigService是可以接受notifications作为参数的啊~

**Comment by zhouruizr** [comment]
大佬能否是否有办法优化啊，我们线上3台configservice都经常出现访问无响应的情况~~急~

**Comment by LabelZhou** [comment]
@pengweiqhca  此处确实可以复用.

**Comment by pengweiqhca** [comment]
新包已经发布
