### ISSUE TITLE
监听配置变化事件

### ISSUE THREAD

**Issue by CarlosAdmin** [ctripcorp/apollo.net#125]
net core 里面怎样实现监听配置变化呢 像这样
 ` ApolloConfigurationManager.Manager.GetConfig("application").Result.ConfigChanged 
`
可以明确知道是哪个Key改动了

**Comment by pengweiqhca** [comment]
使用IOptionsMonitor<TOptions>，不能监听某个key变更，但可以监听整体是否有变更。
apollo的变更监听是客户端实现的

**Comment by CarlosAdmin** [comment]
明白，监控配置变化使用IOptionsMonitor 已经能获取到

**Comment by ihenjoy** [comment]
> 明白，监控配置变化使用IOptionsMonitor 已经能获取到
如何处理的，可以共享下？

**Comment by ihenjoy** [comment]
> 

这是监听事个ConfigurationProvider?

**Comment by pengweiqhca** [comment]
> > 
> 
> 这是监听事个ConfigurationProvider?

是的
