### ISSUE TITLE
传统asp.net集成后出现xml解析错误

### ISSUE THREAD

**Issue by comvir** [ctripcorp/apollo.net#126]
![image](https://user-images.githubusercontent.com/7907986/88995082-60838b00-d31c-11ea-8a7a-38e10bb96d95.png)
这个该如何解决？

**Comment by pengweiqhca** [comment]
你本身的key重复了。&lt;appSettings&gt;不是这样添加的

**Comment by pengweiqhca** [comment]
这个是你的web.config配置重复了。
你是不是两个包都使用了？

**Comment by comvir** [comment]
本意是想将本地的web.config整个复制到配置中心，通过xml一次加载。appsetting确认是没有重复的

**Comment by pengweiqhca** [comment]
参考https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.AspNet.Demo

**Comment by pengweiqhca** [comment]
找到一个[config2json](https://github.com/andrewlock/dotnet-config2json)的工具
