### ISSUE TITLE
请问openapi 这个包具体怎么用？

### ISSUE THREAD

**Issue by Ivin-yang** [ctripcorp/apollo.net#127]
大佬，文档没有介绍，也没有使用说明，看您的代码一头雾水呀，请您指点一下

**Comment by pengweiqhca** [comment]
注入IOpenApiFactory，通过IOpenApiFactory来操作一切

**Comment by Ivin-yang** [comment]
通过IOpenApiFactory来操作一切
您说的操作是包括什么呢
比如读取和创造么？
有没有具体的文档说明参考一下呢
谢谢大佬指点！

**Comment by pengweiqhca** [comment]
官方文档https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0
代码则有xml注释

**Comment by Ivin-yang** [comment]
CreateNamespaceClient
CreateAppClusterClient

IOpenApiFactory就使用这两个方法么  
这俩方法是创建新的集群和命名空间吗？那我要想读取现有的命名空间呢？

xml注释我没有找到

再次感谢！

**Comment by Ivin-yang** [comment]
还有一个问题想请教您
.netcore 使用apollo的配置是在Program中的CreateHostBuilder里添加的
具体代码如下：
  public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .ConfigureAppConfiguration((context, builder) =>
             {
                 builder.AddApollo(builder.Build().GetSection("apollo"))
                        .AddDefault()
                        .AddNamespace("publicCore")
                        .AddNamespace("application");
             })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

我想把命名空间的配置放在appsettings.json 可以吗 
我看java那边的集群好像是可以在配置文件里写入的

谢谢您

**Comment by pengweiqhca** [comment]
> CreateNamespaceClient
> CreateAppClusterClient
> 
> IOpenApiFactory就使用这两个方法么
> 这俩方法是创建新的集群和命名空间吗？那我要想读取现有的命名空间呢？
> 
> xml注释我没有找到
> 
> 再次感谢！

继续点方法啊

**Comment by pengweiqhca** [comment]
> 还有一个问题想请教您
> .netcore 使用apollo的配置是在Program中的CreateHostBuilder里添加的
> 具体代码如下：
> public static IHostBuilder CreateHostBuilder(string[] args) =>
> Host.CreateDefaultBuilder(args)
> .ConfigureAppConfiguration((context, builder) =>
> {
> builder.AddApollo(builder.Build().GetSection("apollo"))
> .AddDefault()
> .AddNamespace("publicCore")
> .AddNamespace("application");
> })
> .ConfigureWebHostDefaults(webBuilder =>
> {
> webBuilder.UseStartup();
> });
> 
> 我想把命名空间的配置放在appsettings.json 可以吗
> 我看java那边的命名空间好像是可以在配置文件里写入的
> 
> 谢谢您

等我添加新功能

**Comment by Ivin-yang** [comment]
后续一直关注您的更新
好的 再次感谢！

**Comment by pengweiqhca** [comment]
https://www.nuget.org/packages/Com.Ctrip.Framework.Apollo.Configuration/2.4.1
https://github.com/ctripcorp/apollo.net/pull/129

**Comment by Ivin-yang** [comment]
支持从配置中读取apollo namespace（key apollo:Namespaces，值为数组，后面优先）

请问这个配置读取 怎么读取？
谢谢！

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.Configuration#三客户端用法
