### ISSUE TITLE
aspnetcore2.2 linux:centos启动时 报System.Net.Http.Formatting找不到

### ISSUE THREAD

**Issue by kaanid** [ctripcorp/apollo.net#131]
## Centos7

`10:37:11 [Warn] Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) - Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
10:37:11 [Warn] Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) - Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
10:37:11 [Warn] Long polling failed, will retry in 1 seconds. appId: dm-predmpriapi, cluster: default, namespace: appsettings.json, long polling url: , reason: Get config services failed from http://testconfig.xxx.xxx:6080/services/config?appId=dm-predmpriapi&ip=10.81.52.223 [Cause: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
`

**Comment by kaanid** [comment]
publish 里是有这个文件的：
System.Net.Http.Formatting，产品版本:5.2.7-61128

**Comment by kaanid** [comment]
## sdk:

dotnet run  正常

## runtime:

1. dotnet publish -c Release -r linux-x64
2. /bin/Release/netcoreapp2.2/linux-x64/publish
3. dotnet xx.dll 不正常

**Comment by pengweiqhca** [comment]
Com.Ctrip.Framework.Apollo和Com.Ctrip.Framework.Apollo.Configuration的版本呢？

**Comment by kaanid** [comment]
> Com.Ctrip.Framework.Apollo和Com.Ctrip.Framework.Apollo.Configuration的版本呢？

刚刚，升级了dotnet 到3.1.401 正常了。感谢。

想建议把Microsoft.AspNet.WebApi.Client依赖去掉
