### ISSUE TITLE
meter多实例节点，.net core这个客户端不支持逗号多个实例，但是java的客户端是支持的

### ISSUE THREAD

**Issue by marjezhang** [ctripcorp/apollo.net#135]
![image](https://user-images.githubusercontent.com/12440254/95346588-9c276c00-08ee-11eb-87e1-48e146fef550.png)
这里的uri 没有逗号分离多个节点路径的方法。
希望有加入这个功能，蛮重要的。

但是java有个issue1.1.0就修复了：
![image](https://user-images.githubusercontent.com/12440254/95346859-da249000-08ee-11eb-8d35-0faa5f9e31c8.png)

**Comment by pengweiqhca** [comment]
[2.4.2实现](https://www.nuget.org/packages/Com.Ctrip.Framework.Apollo/2.4.2)
