### ISSUE TITLE
升级到ASP.NET Core 3.1

### ISSUE THREAD

**Issue by visionding** [ctripcorp/apollo.net#137]
ASP.NET Core 3.0已经用IHostBuilder替换IWebHostBuilder，参见https://docs.microsoft.com/zh-cn/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#hostbuilder-replaces-webhostbuilder，AddApollo扩展方法应该要加到IHostBuilder上面了

**Comment by pengweiqhca** [comment]
已经有[Com.Ctrip.Framework.Apollo.ExtensionsHosting](https://www.nuget.org/packages/Com.Ctrip.Framework.Apollo.ExtensionsHosting/)包

**Comment by wongchance** [comment]
@pengweiqhca 这个具体有CreateWebHostBuilder的demo方法吗  支持netcore3的

**Comment by pengweiqhca** [comment]
> @pengweiqhca 这个具体有CreateWebHostBuilder的demo方法吗 支持netcore3的

``` C#
hostBuilder.AddApollo()啊
```

**Comment by wongchance** [comment]
public static IWebHostBuilder CreateHostBuilder(string[] args, string port, IConfiguration configuration) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, builder) =>
                {
                    builder.AddApollo("com.404abc.service", "http://192.168.0.201:8080/")
                    .AddDefault() 
                    .AddNamespace("common")
                    .AddNamespace("application");
                })
                .UseStartup<Startup>();
`

configuration里的provider有apollo，但是data是空；
![image](https://user-images.githubusercontent.com/6054847/96837453-073d7a80-1479-11eb-823b-9416000f9353.png)
![image](https://user-images.githubusercontent.com/6054847/96854351-f4817080-148d-11eb-940f-b7a5daa632f3.png)
这是杂回事呢

**Comment by wongchance** [comment]
> ```
>   public static IWebHostBuilder CreateHostBuilder(string[] args, string port, IConfiguration configuration) =>
>         WebHost.CreateDefaultBuilder(args)
>             .ConfigureAppConfiguration((hostingContext, builder) =>
>             {
>                 builder.AddApollo("com.404abc.service", "http://192.168.0.201:8080/")
>                 .AddDefault() 
>                 .AddNamespace("common")
>                 .AddNamespace("application");
>             })
>             .UseStartup<Startup>();
> ```
> 
> `
> 
> configuration里的provider有apollo，但是data是空；
> ![image](https://user-images.githubusercontent.com/6054847/96837453-073d7a80-1479-11eb-823b-9416000f9353.png)
> ![image](https://user-images.githubusercontent.com/6054847/96854351-f4817080-148d-11eb-940f-b7a5daa632f3.png)
> 这是杂回事呢

`"apollo": {
    "AppId": "com.404abc.product",
    "MetaServer": "http://192.168.0.201:8080/",
    "ConfigServer": [ "http://192.168.0.201:8080/", "http://127.0.0.1:8080/" ],
    "Env": "Dev"
  },`
部署到docker的问题，
配置了ConfigServer解决

@visionding 可以参考这个
        ```
public static IHostBuilder CreateHostBuilder(string[] args) =>
         Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((hostingContext, builder) =>
            {
                var section = builder.Build().GetSection("apollo").GetChildren().ToArray();
                builder.AddApollo(builder.Build().GetSection("apollo"))
                //r.AddApollo("com.404abc.product", "http://192.168.0.201:8080/")
                    .AddDefault().AddNamespace("common").AddNamespace("application"); ;
            })
           .ConfigureWebHostDefaults(webBuilder =>
           {
               webBuilder
               .UseStartup<Startup>();
           });
```

**Comment by visionding** [comment]
> ```
> "apollo": {
>     "AppId": "com.404abc.product",
>     "MetaServer": "http://192.168.0.201:8080/",
>     "ConfigServer": [ "http://192.168.0.201:8080/", "http://127.0.0.1:8080/" ],
>     "Env": "Dev"
>   },
> ```
> 
> 部署到docker的问题，
> 配置了ConfigServer解决
> 
> @visionding 可以参考这个
> 
> ```
> public static IHostBuilder CreateHostBuilder(string[] args) =>
>          Host.CreateDefaultBuilder(args)
>             .ConfigureAppConfiguration((hostingContext, builder) =>
>             {
>                 var section = builder.Build().GetSection("apollo").GetChildren().ToArray();
>                 builder.AddApollo(builder.Build().GetSection("apollo"))
>                 //r.AddApollo("com.404abc.product", "http://192.168.0.201:8080/")
>                     .AddDefault().AddNamespace("common").AddNamespace("application"); ;
>             })
>            .ConfigureWebHostDefaults(webBuilder =>
>            {
>                webBuilder
>                .UseStartup<Startup>();
>            });
> ```

嗯，我也是参考源代码里面写的
