### ISSUE TITLE
请问Apollo.NET是否支持WinForm/WPF 客户端 进行拉取配置？

### ISSUE THREAD

**Issue by robyle** [ctripcorp/apollo.net#138]
你好，假设我们在做一些CS模式的软件，想用起Apollo，是否有案例支持，相关的安全策略是否会存在问题？我这边实践出来的情况是必须需要放开Eureka端口和AppId的授权密钥。  请问是否支持一个密钥进行，然后通过正常的Web 端口就可以达到访问和监听修改的目的？

**Comment by pengweiqhca** [comment]
不适合C/S模式，因为配置会缓存到客户端

**Comment by robyle** [comment]
好的，谢谢。我昨天实践了一天，确实在使用上有很多障碍。但是有一个障碍我想问下看是否可以解决？
1.Apollo基于docker拉起来的，存在端口映射的情况，我配置的是本地端口映射出来的地址，每次把客户端拉起来的时候服务器老返回docker的地址和端口。请问咋们.NET 客户端是否可以支持像Java客户端一样调用setProproty 来改变config-server url地址端口。

![image](https://user-images.githubusercontent.com/11662528/100712693-1e637680-33ee-11eb-81d1-68cd7b0860c8.png)


2.项目开启了访问密钥，Apollo.NET的客户端如何有效的配置该密钥，我找到了很久没看到有效的设置入口。是不是咋们.NET客户端不支持？

**Comment by pengweiqhca** [comment]
> 好的，谢谢。我昨天实践了一天，确实在使用上有很多障碍。但是有一个障碍我想问下看是否可以解决？
> 1.Apollo基于docker拉起来的，存在端口映射的情况，我配置的是本地端口映射出来的地址，每次把客户端拉起来的时候服务器老返回docker的地址和端口。请问咋们.NET 客户端是否可以支持像Java客户端一样调用setProproty 来改变config-server url地址端口。
> 
> ![image](https://user-images.githubusercontent.com/11662528/100712693-1e637680-33ee-11eb-81d1-68cd7b0860c8.png)
> 
> 2.项目开启了访问密钥，Apollo.NET的客户端如何有效的配置该密钥，我找到了很久没看到有效的设置入口。是不是咋们.NET客户端不支持？

[查看4.2和4.3](https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.ConfigurationManager#42-如何跳过meta-service的服务发现)

**Comment by robyle** [comment]
> > 好的，谢谢。我昨天实践了一天，确实在使用上有很多障碍。但是有一个障碍我想问下看是否可以解决？
> > 1.Apollo基于docker拉起来的，存在端口映射的情况，我配置的是本地端口映射出来的地址，每次把客户端拉起来的时候服务器老返回docker的地址和端口。请问咋们.NET 客户端是否可以支持像Java客户端一样调用setProproty 来改变config-server url地址端口。
> > ![image](https://user-images.githubusercontent.com/11662528/100712693-1e637680-33ee-11eb-81d1-68cd7b0860c8.png)
> > 2.项目开启了访问密钥，Apollo.NET的客户端如何有效的配置该密钥，我找到了很久没看到有效的设置入口。是不是咋们.NET客户端不支持？
> 
> [查看4.2和4.3](https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.ConfigurationManager#42-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)

谢谢，我的困惑已经基本得到解决了，非常感谢！ 就是 config.getProperty这块的功能我们C#客户端暂不支持还是说另有其它通道进行可以进行设置？

**Comment by pengweiqhca** [comment]
> > > 好的，谢谢。我昨天实践了一天，确实在使用上有很多障碍。但是有一个障碍我想问下看是否可以解决？
> > > 1.Apollo基于docker拉起来的，存在端口映射的情况，我配置的是本地端口映射出来的地址，每次把客户端拉起来的时候服务器老返回docker的地址和端口。请问咋们.NET 客户端是否可以支持像Java客户端一样调用setProproty 来改变config-server url地址端口。
> > > ![image](https://user-images.githubusercontent.com/11662528/100712693-1e637680-33ee-11eb-81d1-68cd7b0860c8.png)
> > > 2.项目开启了访问密钥，Apollo.NET的客户端如何有效的配置该密钥，我找到了很久没看到有效的设置入口。是不是咋们.NET客户端不支持？
> > 
> > 
> > [查看4.2和4.3](https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.ConfigurationManager#42-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)
> 
> 谢谢，我的困惑已经基本得到解决了，非常感谢！ 就是 config.getProperty这块的功能我们C#客户端暂不支持还是说另有其它通道进行可以进行设置？

`config.GetProperty`

**Comment by robyle** [comment]
> GetProperty

哦，我说的是如何SetProperty.

**Comment by pengweiqhca** [comment]
不支持

**Comment by robyle** [comment]
> 不支持

好的，了解。感谢了！
