### ISSUE TITLE
关于GetSection问题

### ISSUE THREAD

**Issue by lws62336426** [ctripcorp/apollo.net#139]
原来框架里自带GetSection方法可以读取到Json节点信息。现改为Apollo的话再用原来的GetSection就读取不到信息了。是不是意味着之前所有用到GetSection方法的地方都需要改成GetValue了呢

**Comment by pengweiqhca** [comment]
没有区别的，可能是你配置错误了。如果不想将json转成property就直接使用josn格式的namespace

**Comment by lws62336426** [comment]
我应该怎么设置呢。我看配置页面上只有key-value的形式

**Comment by pengweiqhca** [comment]
> 我应该怎么设置呢。我看配置页面上只有key-value的形式

![添加Namespace](https://user-images.githubusercontent.com/3982826/101112265-dfb10480-3617-11eb-9af7-3bf83c6996a8.png)

**Comment by lws62336426** [comment]
![image](https://user-images.githubusercontent.com/16740090/101114095-b85c3680-361b-11eb-83a9-8175d72d05e4.png)
![image](https://user-images.githubusercontent.com/16740090/101114148-d32eab00-361b-11eb-9f5e-c465520e1256.png)
大神。我这里听取你的指点设置了。但是好像还是读取不到。是代码的问题吗

**Comment by lws62336426** [comment]
可以了。谢谢
