### ISSUE TITLE
.net core客户端怎么自定义配置文件缓存路径

### ISSUE THREAD

**Issue by wmhiness** [ctripcorp/apollo.net#141]
1、.net core客户端怎么自定义配置文件缓存路径
2、命名空间添加之后怎么修改已经添加的命名空间名称

**Comment by xia1727796989** [comment]
.net framework 同问！

**Comment by pengweiqhca** [comment]
> 1、.net core客户端怎么自定义配置文件缓存路径
> 2、命名空间添加之后怎么修改已经添加的命名空间名称

1：配置LocalCacheDir
2：暂不支持

**Comment by pengweiqhca** [comment]
> .net framework 同问！

配置apollo:LocalCacheDir或者配置apollo.LocalCacheDir

**Comment by wmhiness** [comment]
已经解决  thanks
