### ISSUE TITLE
请问如何读取apollo配置的xml文件

### ISSUE THREAD

**Issue by 3zengzz** [ctripcorp/apollo.net#148]
我想把日志组件nlog的配置文件放进apollo，
![image](https://user-images.githubusercontent.com/30330939/106075069-e6f01c80-6147-11eb-868d-ca0e9bf85196.png)
但是程序生成的缓存文件是
![image](https://user-images.githubusercontent.com/30330939/106075116-fb341980-6147-11eb-9459-edb0e209a8ab.png)
然后程序运行报错
程序的代码是这样的
![image](https://user-images.githubusercontent.com/30330939/106075166-13a43400-6148-11eb-955c-36bd0cc4c9c3.png)
请问要怎么怎么做才能读xml呢

**Comment by pengweiqhca** [comment]
nlog应该不支持从IConfiguration读取配置（文档没有查到支持），那么只能将nlog配置到properties格式的namespace里。
xml格式的namespace将内容打散，不适用于直接读取整个xml。
