### ISSUE TITLE
超时时间要能进行配置

### ISSUE THREAD

**Issue by shiweichuan** [ctripcorp/apollo.net#149]
程序使用docker进行部署，刚启动时候，经常会超时，导致没有取到配置。
var response = await _httpUtil.DoGetAsync<IList<ServiceDto>?>(url[index % url.Count], 2000).ConfigureAwait(false);
这里超时时间是否太短了，最好要放到option里面能配置。

控制台输出：
17:30:10 [Debug] refresh config services
17:30:10 [Debug] refresh config for namespace: application
17:30:12 [Warn] Could not complete get operation - Could not complete get operation [Cause: The operation has timed out.]

**Comment by pengweiqhca** [comment]
更新到[2.4.4](https://www.nuget.org/packages/Com.Ctrip.Framework.Apollo/2.4.4)，使用Timeout配置值（默认5000ms）
