### ISSUE TITLE
解析json

### ISSUE THREAD

**Issue by YiMing668** [ctripcorp/apollo.net#151]
{ "Host": "127.0.0.1", "Prot": 6379, "DB": 0 }
	public class RedisConnOptions
	{
		public string Host { get; set; }
		public int DB { get; set; } = 0;
		public int Prot { get; set; }
	}

可不可以不需要自己去序列化转换成对象,有没有提供的直接通过泛型方法获取对象的

**Comment by pengweiqhca** [comment]
这个不属于Apollo问题啊
