### ISSUE TITLE
Apollo.Net初始化时参数优先级问题

### ISSUE THREAD

**Issue by laoshancun** [ctripcorp/apollo.net#154]
## 问题描述

在初始化Apollo时，支持从配置文件`AppSettings`及环境变量获取相关参数，但是优先级存在小问题，默认是配置文件优先，当配置文件值为空时才会读取环境变量。

## 预期结果：
建议修改为环境变量优先

## 修改内容 
`Com.Ctrip.Framework.Apollo.Util.ConfigUtil.GetAppConfig`

**Comment by pengweiqhca** [comment]
这个行为和是java版本一致

**Comment by laoshancun** [comment]
据查看代码，cluster/env/metaserver等参数都是环境变量优先，然后才是配置文件。
详情请查阅[源代码](https://github.com/ctripcorp/apollo/blob/master/apollo-core/src/main/java/com/ctrip/framework/foundation/internals/provider/DefaultServerProvider.java#L149)

**Comment by laoshancun** [comment]
这也正是与java的client不一致的地方
## java
![image](https://user-images.githubusercontent.com/4952748/110098954-b9982d80-7ddb-11eb-9a1f-1b2915fbd868.png)
![image](https://user-images.githubusercontent.com/4952748/110098973-be5ce180-7ddb-11eb-8b1b-3de0cdcc0365.png)
## csharp
![image](https://user-images.githubusercontent.com/4952748/110099283-15fb4d00-7ddc-11eb-8162-6c3bdefe13d3.png)

**Comment by LabelZhou** [comment]
> 这也正是与java的client不一致的地方
> 
> ## java
> ![image](https://user-images.githubusercontent.com/4952748/110098954-b9982d80-7ddb-11eb-9a1f-1b2915fbd868.png)
> ![image](https://user-images.githubusercontent.com/4952748/110098973-be5ce180-7ddb-11eb-8b1b-3de0cdcc0365.png)
> 
> ## csharp
> ![image](https://user-images.githubusercontent.com/4952748/110099283-15fb4d00-7ddc-11eb-8162-6c3bdefe13d3.png)

这俩是一样的.. 提供一下最小示例代码吧

**Comment by LabelZhou** [comment]
> 这也正是与java的client不一致的地方
> 
> ## java
> ![image](https://user-images.githubusercontent.com/4952748/110098954-b9982d80-7ddb-11eb-9a1f-1b2915fbd868.png)
> ![image](https://user-images.githubusercontent.com/4952748/110098973-be5ce180-7ddb-11eb-8b1b-3de0cdcc0365.png)
> 
> ## csharp
> ![image](https://user-images.githubusercontent.com/4952748/110099283-15fb4d00-7ddc-11eb-8162-6c3bdefe13d3.png)

不好意思.刚回复了错误言论..确实是不一样的.. :(

>

**Comment by laoshancun** [comment]
已提交PR.
