### ISSUE TITLE
关于.NETCORE3.1使用apollo异常问题

### ISSUE THREAD

**Issue by a194259440** [ctripcorp/apollo.net#158]
> * [ ]  我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
> * [ ]  我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
> * [ ]  我已经仔细检查过[FAQ](https://ctripcorp.github.io/apollo/#/zh/faq/common-issues-in-deployment-and-development-phase)
> 
> **描述bug**
> 
> 简洁明了地描述一下bug
> 当使用.NETCORE3.1的项目在启动时，会发生错误
> **复现**
> 
> 通过如下步骤可以复现：
> 
> 1. 创建.netcore3.1web项目
> 2. 在项目中引用Com.Ctrip.Framework.Apollo.Configuration 2.4.1
> 3. 在startup中使用apollo
> 4. 运行项目即复现
> 
> **期望**
> 
> 简介明了地描述你希望正常情况下应该发生什么
> 在.netcore2.2上，项目可正常运行，新项目中使用.netcore3.1，以便于后续升级成.netcore5.0
> **截图**
> 
> 如果可以，附上截图来描述你的问题
> ![1615201288(1)](https://user-images.githubusercontent.com/43952916/110313185-0b8dbd00-8041-11eb-8ce3-6b4a1c0f3807.jpg)
> ![1615201302(1)](https://user-images.githubusercontent.com/43952916/110313188-0cbeea00-8041-11eb-80d1-8b4d7ef46f09.jpg)
> 
> ### 额外的细节和日志
> * 版本 Com.Ctrip.Framework.Apollo.Configuration 2.4.1
> * 错误日志 System.TypeLoadException:“Method 'get_Secret' in type 'Com.Ctrip.Framework.Apollo.ApolloOptions' from assembly 'Com.Ctrip.Framework.Apollo.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=6cdd45170aaef7fc' does not have an implementation.”
> * 配置：I5-8400
> * 平台和操作系统 windows

**Comment by pengweiqhca** [comment]
Com.Ctrip.Framework.Apollo.Configuration和Com.Ctrip.Framework.Apollo中间有个版本脱节，升级Com.Ctrip.Framework.Apollo.Configuration包解决

**Comment by a194259440** [comment]
好的，抱歉，忘了回复，由于项目比较急，我们重新降为.NETCORE2.2，下一个项目，我们将尝试使用.NETCORE3.1，感谢回答

**Comment by pengweiqhca** [comment]
> 你好 我采用的是官方集成 代码如下：
> ![image](https://user-images.githubusercontent.com/47095031/113258289-5a580b00-92fe-11eb-813a-141f8561d5dc.png)
> 但是使用的时候apollo 取值不到
> 我使用的是：Configuration.GetSection("key")

输出日志看看https://github.com/ctripcorp/apollo.net#二日志输出
