### ISSUE TITLE
将Namespaces配置在appsettings里面,不起作用

### ISSUE THREAD

**Issue by ArchitectAllen1** [ctripcorp/apollo.net#160]
我使用的是net5
![image](https://user-images.githubusercontent.com/66348603/115806652-c1f30900-a419-11eb-8f7b-23dc743c7648.png)
![image](https://user-images.githubusercontent.com/66348603/115806967-51002100-a41a-11eb-9047-c1011a4f386b.png)
![image](https://user-images.githubusercontent.com/66348603/115807041-6b39ff00-a41a-11eb-8cf8-7fbb50614203.png)

**Comment by ArchitectQin** [comment]
我用手动AddNamespace就没问题
![image](https://user-images.githubusercontent.com/66348603/115807303-f61af980-a41a-11eb-99d9-54e2c2dca7d5.png)
![image](https://user-images.githubusercontent.com/66348603/115807337-059a4280-a41b-11eb-95b7-3fd8132cc4d7.png)

**Comment by ArchitectQin** [comment]
3.1也不能用

**Comment by pengweiqhca** [comment]
你看看`builder.Build().GetSection("apollo").Get<ApolloOptions>().Namespaces`是否有值

**Comment by ArchitectQin** [comment]
哥哥 不好意思啊,我用的是2.4.0版本,升级以后就ok了.
