### ISSUE TITLE
apollo使用容器方式会导致客户端无法连接服务器

### ISSUE THREAD

**Issue by QQ897878763** [ctripcorp/apollo.net#161]
因为docker-compose会生成一个类型为bridge的自定义网络，服务器是采取端口映射方式与apollo实现互通。
但是当DotnetCore客户端在执行IConfigRepository的GetConfig()方法时候应该是从服务注册中心获取了apollo的实际地址并与之进行http通信，问题就是服务注册中心登记的地址是docker自定义网络的地址，比如apollo docker容器的ip是172.18.0.3 则服务注册中心返回的地址则是`http://172.18.0.3:8080/configs/UAT-CRM/default/XXXX?ip=xxx`，实际上这里把172.18.0.3变更为服务器宿主的ip地址即可

**Comment by nobodyiam** [comment]
see #73

**Comment by QQ897878763** [comment]
可以通过环境变量解决 谢谢
