### ISSUE TITLE
环境是用的netcore3.1 获取有占位符的value值没替换占位符！

### ISSUE THREAD

**Issue by ClementeGao** [ctripcorp/apollo.net#165]
![image](https://user-images.githubusercontent.com/16145998/124911371-40297980-e01f-11eb-977f-bc3b4243ff35.png)

**Comment by pengweiqhca** [comment]
默认IConfiguration是不支持点位符（JAVA是通过Spring支持的），如果想要支持点位符需要使用Tuhu.Extensions.Configuration.Placeholder包

**Comment by ClementeGao** [comment]
好的，感谢
