### ISSUE TITLE
.net 4.5  不支持相对路径   

### ISSUE THREAD

**Issue by rewrrtf** [ctripcorp/apollo.net#17]

**Comment by nobodyiam** [comment]
具体一点？

**Comment by rewrrtf** [comment]
Apollo.LocalCacheDir   
 在web项目下，这个配置项的如果是相对地址 相对的不是项目跟目录 ，而是iis根目录或者C盘

**Comment by rewrrtf** [comment]
4.5  web项目中 apollo的初始化必须在 globle  application start 中进行 ，
在具体的请求线程中初始化 ，必死

**Comment by nobodyiam** [comment]
能提供个demo吗？我们公司大量使用貌似都没有这个问题，你用的是master分支还是dotnet-core分支？

**Comment by gityes** [comment]
public string DefaultLocalCacheDir
        {
            get
            {
                return string.Format("C:\\opt\\data\\{0}", AppId);
            }
        }
这个地方写的绝对路径，我在MAC上开发时会报错。。。。。。

**Comment by nobodyiam** [comment]
好吧，现在时代进步了，都可以在mac上开发了。。。那有啥方法可以判断吗？

**Comment by yuanrui** [comment]
cache可以放到 Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) 里面
