### ISSUE TITLE
.net core的版本没有读\opt\settings\server.properties的配置

### ISSUE THREAD

**Issue by runningjayden** [ctripcorp/apollo.net#21]

**Comment by nobodyiam** [comment]
恩，.net core的版本看上去都是读的AppSettings里面的配置

**Comment by pengweiqhca** [comment]
不会依赖具体的配置源，只会依赖IConfiguration。如果你需要使用server.properties，请自己将配置源添加到IConfigurationBuilder里

**Comment by pengweiqhca** [comment]
> 需要自己注册个 provider 吗？Environment 变量 IDC 可以默认被使用吗？

`AddApollo`时使用另一个传入`IApolloOptions`的重载

**Comment by jerviscui** [comment]
> > 需要自己注册个 provider 吗？Environment 变量 IDC 可以默认被使用吗？
> 
> `AddApollo`时使用另一个传入`IApolloOptions`的重载

恩，好的，我也是这样做的，自己读取的配置
