### ISSUE TITLE
Get operation failed for ....

### ISSUE THREAD

**Issue by zzyykk123456** [ctripcorp/apollo.net#23]
本地电脑上配置和启动Apollo，测试.net 的Demo 出现下图错误码500。
![image](https://user-images.githubusercontent.com/12078303/47340588-55c0ae80-d6d1-11e8-89a8-d86799e792f2.png)
![image](https://user-images.githubusercontent.com/12078303/47340677-8e608800-d6d1-11e8-8c20-6b93f80a9484.png)

**Comment by nobodyiam** [comment]
直接在浏览器中输入报错的地址，看看具体的错误信息

**Comment by zzyykk123456** [comment]
![image](https://user-images.githubusercontent.com/12078303/47542386-bb01e300-d90f-11e8-95cd-0198e2c5495e.png)

**Comment by nobodyiam** [comment]
是正确的，之前客户端访问的报错是服务端返回了500

**Comment by nobodyiam** [comment]
可以参考一下 https://github.com/ctripcorp/apollo/issues/1609 ，估计服务端升级到spring 5有关，在master分支已经修复了。

**Comment by zzyykk123456** [comment]
ok

**Comment by nobodyiam** [comment]
1.1.2版本已经release，包含了该问题修复，详见 https://github.com/ctripcorp/apollo/releases
