### ISSUE TITLE
下载下来有很多报错

### ISSUE THREAD

**Issue by gebiWangshushu** [ctripcorp/apollo.net#26]
下载下来有很多报错
这是第一次生成：
![image](https://user-images.githubusercontent.com/27838829/48944114-6f6b4500-ef60-11e8-9573-47ac3758d8ad.png)

**Comment by pengweiqhca** [comment]
请使用git clone或者删除Microsoft.SourceLink.GitHub包

**Comment by gebiWangshushu** [comment]
感谢，[掩面]
