### ISSUE TITLE
请求增加使用文档

### ISSUE THREAD

**Issue by Varorbc** [ctripcorp/apollo.net#28]
[原来的使用文档](https://github.com/ctripcorp/apollo/wiki/.Net%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)已经不适用了，麻烦更新文档内容

**Comment by moyuanhui** [comment]
多环境是不是不适用呀？

**Comment by nobodyiam** [comment]
恩，原来的文档是针对master分支的，dotnet core的版本确实缺失了文档，@pengweiqhca 不知是否可以补充一些到README.md里面？后续我可以补充到wiki上去~

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/pull/30

**Comment by Varorbc** [comment]
@pengweiqhca 我看配置文件里还有DataCenter SubEnv Authorization等参数我看文档里都没有提到

**Comment by pengweiqhca** [comment]
@Varorbc 这几个我们公司暂时还没有使用到，也没有经过严格测试，不敢写进去，希望大家提交PR来完善

**Comment by Varorbc** [comment]
那就是目前这几个字段可以忽略的是吧？

**Comment by moyuanhui** [comment]
client源码有个问题，会获取远程主机的真实ip地址，就像我部署在k8s中，client会获取pod的集群地址，但是集群外部是不可访问的，就导致获取不到配置的问题

**Comment by Varorbc** [comment]
好的，我了解了，我关闭这个问题了

**Comment by pengweiqhca** [comment]
@moyuanhui 其实这个IP不会影响你的配置获取，即使是一个错误的
