### ISSUE TITLE
多环境的配置到底怎么用，搞什么？

### ISSUE THREAD

**Issue by moyuanhui** [ctripcorp/apollo.net#29]

**Comment by pengweiqhca** [comment]
appsettings.json
``` JSON
{
  "apollo": {
    "AppId": "",
    "MetaServer": "",
    "Env": "PRO"
  }
}
```
appsettings.Development.json
``` JSON
{
    "apollo": {
        "MetaServer": "",
        "Env": "DEV"
    }
}

```

**Comment by moyuanhui** [comment]
{
  "apollo": {
    "AppId": "",
    "Cluster": "default",
    "DevServer": "",
    "FatServer": "",
    "UatServer": "",
    "ProdServer": "",
    "IsRemoteUrl": true
  }
}
个人源码已经修改了

**Comment by pengweiqhca** [comment]
重复造轮子
