### ISSUE TITLE
有没有计划支持asp.net core

### ISSUE THREAD

**Issue by yaozhenfa** [ctripcorp/apollo.net#3]
我司想采用归司的配置中心，但是当前所有的业务系统均采用asp.net core，正打算阅读源码改成支持asp.net core。

**Comment by nobodyiam** [comment]
暂时没有计划。

**Comment by badounan** [comment]
是rest接口吗，有没有详细的接口 api文档啊，我们也是基于.net core的，想使用apollo

**Comment by nobodyiam** [comment]
参考下[其它语言客户端接入指南](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)，也可以具体看下.net的实现吧，应该差不太多

**Comment by nobodyiam** [comment]
@yaozhenfa @badounan 

@pengweiqhca 提交了一个PR支持.net core，参见 #4 ，由于代码变化太大，所以目前该代码合到了[dotnet-core](https://github.com/ctripcorp/apollo.net/tree/dotnet-core)分支，后续如有对.net core相关的改动，都可以基于该分支。
