### ISSUE TITLE
.net core版本value值对特定数据格式的支持

### ISSUE THREAD

**Issue by Hackcr** [ctripcorp/apollo.net#32]
现在.net core SDK配置的value值只是字符串，如果要支持JSON、XML等特定格式，有什么好的实现方法？

**Comment by nobodyiam** [comment]
json、xml也是字符串，在上层转换一下吧

**Comment by pengweiqhca** [comment]
@Hackcr https://github.com/ctripcorp/apollo.net/tree/dotnet-core/Apollo.Configuration#四faq
