### ISSUE TITLE
内网客户端程序请求配置超时

### ISSUE THREAD

**Issue by sofuny** [ctripcorp/apollo.net#42]
我同一个程序在本地是可以得到配置信息的，但把程序移到另一台服务器后就提示请求超时了
[Warn] Long polling failed, will retry in 120 seconds. appId: parttask, cluster: dev, names
pace: application, long polling url: , reason: Get config services failed from http://192.168.5.141:
8080//services/config?appId=parttask&ip=192.168.5.244 [Cause: Could not complete get operation [Caus
e: 操作已超时。]]
![image](https://user-images.githubusercontent.com/15317714/51653845-40a93380-1fd0-11e9-9ebd-278b8641f54f.png)
实例中95是我本地的客户端
想问一下我可以从什么方面检查是什么问题导致请求不到配置

**Comment by nobodyiam** [comment]
` http://192.168.5.141:8080//services/config?appId=parttask&ip=192.168.5.244`，这个访问超时

**Comment by sofuny** [comment]
图片放不上来
[{"appName":"APOLLO-CONFIGSERVICE","instanceId":"192.168.5.141:apollo-configservice:8080","homepageUrl":"http://192.168.5.141:8080/"}]
这是我在244服务器的浏览器中请求的结果
这样应该是表示可以访问吧

**Comment by nobodyiam** [comment]
访问超时和代码没啥关系啊，看下是不是响应太慢导致的，默认的connect timeout是1秒，read timeout是5秒。

**Comment by pengweiqhca** [comment]
Long polling写死的10分钟

**Comment by pengweiqhca** [comment]
Get config services的超时是2秒，重试3次

**Comment by sofuny** [comment]
为了这个问题我弄了四份测试代码，不同的版本
.net framework 4.7.2类库 引用apollo1.3 启动项目为 .net framework 4.7.2  运行正常 配置获取成功
.net framework 4.7.2类库 引用apollo1.5.2 启动项目为  .net framework 4.7.2 运行正常 配置获取失败 请求超时
.net standard类库 引用apollo1.5.2  启动项目为 .net framework 4.7.2  运行正常 配置获取失败  请求超时
.net standard类库 引用apollo1.5.2  启动项目为 .net core 2.2 发布模式独立  运行正常 配置获取成功

不知道为什么中间两项不能获取成功，同一个服务器，同样的环境，获取同一个项目的配置
Windows Server 2008 R2 Standard
.net framework 4.7.2
.net core 2.2

**Comment by sofuny** [comment]
我昨天遇到的问题 是第二种

**Comment by sofuny** [comment]
我也觉得不是代码的问题 实在不行 我之后可能只能把程序改成第一种或第四种了。。。。

**Comment by pengweiqhca** [comment]
你可以试试Demo，我刚才使用Demo测试第二种没有问题
