### ISSUE TITLE
采用web.config中配置的方式(AppSettingsSectionBuilder)配置中心修改后无法将最新配置刷入ConfigurationManager.AppSettings

### ISSUE THREAD

**Issue by flypigarmy** [ctripcorp/apollo.net#45]
core分支，参见Apollo.AspNet.Demo中，采用在web.config中配置的方式<appSettings configBuilders="AppSettingsSectionBuilder">，当配置中心发布配置后，客户端收到了最新配置，opt中的配置文件也是最新的，但是通过ConfigurationManager.AppSettings获取的配置还是旧的。看到源码中ApolloConfigurationBuilder类private void Config_ConfigChanged(object sender, ConfigChangeEventArgs args) => ConfigurationManager.RefreshSection(SectionName);  该事件有触发，但是并没有触发AppSettingsSectionBuilder类的ProcessConfigurationSection来刷新配置

**Comment by pengweiqhca** [comment]
只有`ConfigurationManager.RefreshSection(SectionName)`这个方法，不生效无解
