### ISSUE TITLE
能否支持使用代理请求apollo配置服务器

### ISSUE THREAD

**Issue by zhaokjGH** [ctripcorp/apollo.net#47]
paas服务出口ip太多了，配置服务器添加白名单很麻烦，能否在请求配置服务器的时候主动使用代理来访问呢。

**Comment by zhaokjGH** [comment]
在配置文件中能否新增一个字段来配置代理机器的ip、端口

**Comment by nobodyiam** [comment]
直接设置系统的代理可以吗？

**Comment by zhaokjGH** [comment]
因为程序是部署于azure上的paas服务，不存在实际意义上的机器而且azure的app service plan也是无法设置代理的。

**Comment by zhaokjGH** [comment]
所以直接设置系统代理的方式是行不通的

**Comment by pengweiqhca** [comment]
@zhaokjGH 已发新包添加支持，https://github.com/ctripcorp/apollo.net/pull/48

**Comment by zhaokjGH** [comment]
新包（1.5.2）在使用代理访问apollo配置服务器的时候会一直卡在读取阶段 @pengweiqhca  ，#48

**Comment by pengweiqhca** [comment]
我通过fiddler测试没有此问题

**Comment by zhaokjGH** [comment]
我使用postman直接访问
http://XXXXXX/services/config?appId=1010101也没什么问题，但是在程序中却会出现卡住的情况。

**Comment by pengweiqhca** [comment]
你是用Com.Ctrip.Framework.Apollo.Configuration还是Com.Ctrip.Framework.Apollo.ConfigurationManager

**Comment by zhaokjGH** [comment]
Com.Ctrip.Framework.Apollo.Configuration 这个

**Comment by pengweiqhca** [comment]
有使用`ApolloConfigurationManager`？

**Comment by zhaokjGH** [comment]
没有就使用了一个包
 <PackageReference Include="Com.Ctrip.Framework.Apollo.Configuration" Version="1.5.2" />

**Comment by zhaokjGH** [comment]
Com.Ctrip.Framework.Apollo.Configuration   Version="1.5.2"

**Comment by pengweiqhca** [comment]
建议使用fiddler测试一下，看看卡在哪一步

**Comment by zhaokjGH** [comment]
ok，我试下看看

**Comment by zhaokjGH** [comment]
debug了下发现卡在下载配置这一步了，这个可能是什么造成的呢？

**Comment by pengweiqhca** [comment]
在fiddler里看看是否有返回数据

**Comment by zhaokjGH** [comment]
我发现问题出现在HttpUtil.DoGetAsync<T>(string url, int timeout)中的获取httpClient的地方
timeout在程序中取值有3个  2000、5000（默认）、600000
但是只有在2000的时候， 方法_httpClient.GetOrAdd 才能返回httpclient。其他值都会一直卡在那里。

**Comment by zhaokjGH** [comment]
已解决。
