### ISSUE TITLE
.netcore多环境配置能否根据Env字段值来选择MetaServer的值呢？

### ISSUE THREAD

**Issue by zhaokjGH** [ctripcorp/apollo.net#51]
目前程序使用appId和MetaServer这两个字段就可以获取到配置信息了，而Env字段没起到相应的作用。

能否参照 .net framework的多种环境配置方式，将多环境的meta 都一起写入，然后通过修改env的值来选择相应的meta呢？

**Comment by pengweiqhca** [comment]
可以通过appsettings.{environment}.json来配置不同环境的metaserver

**Comment by zhaokjGH** [comment]
好的，还有个问题就是使用appId和MetaServer这两个字段就可以获取到配置信息了，那么Env配置又起到什么作用呢？还有SubEnv这个字段会起到什么作用呢？因为我再文档上也没看到有关SubEnv字段的介绍。

**Comment by pengweiqhca** [comment]
Env和SubEnv确实没有用
