### ISSUE TITLE
Demo中.net core 2.2初始化配置的时候取不到apollo配置节点内容

### ISSUE THREAD

**Issue by lihui546682631** [ctripcorp/apollo.net#58]
原代码：
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
               .ConfigureAppConfiguration((cotnext, builder) =>
               {
                   // cotnext.Configuration.GetSection("apollo") 读取不到
                   builder.AddApollo(cotnext.Configuration.GetSection("apollo"))
                     .AddDefault(ConfigFileFormat.Xml)
                     .AddDefault(ConfigFileFormat.Json)
                     .AddDefault(ConfigFileFormat.Yml)
                     .AddDefault(ConfigFileFormat.Yaml)
                     .AddDefault();
               })
                .UseStartup<Startup>();
修改后代码：
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
               .ConfigureAppConfiguration((cotnext, builder) =>
               {
                   // builder.Build().GetSection("apollo") 可以读取
                   builder.AddApollo(builder.Build().GetSection("apollo"))
                     .AddDefault(ConfigFileFormat.Xml)
                     .AddDefault(ConfigFileFormat.Json)
                     .AddDefault(ConfigFileFormat.Yml)
                     .AddDefault(ConfigFileFormat.Yaml)
                     .AddDefault();
               })
                .UseStartup<Startup>();

**Comment by lihui546682631** [comment]
望作者验证下是否仅仅.net core 2.2版本有问题

**Comment by pengweiqhca** [comment]
这个是.net core 2.2使用in-process的问题

> 在 ASP.NET Core 2.2.1 或早期版本中，GetCurrentDirectory 会返回 IIS 启动的进程的工作目录而非应用目录（例如，对于 w3wp.exe，是 C:\Windows\System32\inetsrv ）。
> 对于设置应用的当前目录的示例代码，请参阅 [CurrentDirectoryHelpers](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs) 类。 调用 SetCurrentDirectory 方法。 后续 GetCurrentDirectory 调用提供应用的目录。
