### ISSUE TITLE
net core 空指针异常

### ISSUE THREAD

**Issue by cysnet** [ctripcorp/apollo.net#67]

**Comment by cysnet** [comment]
空指针异常
![image](https://user-images.githubusercontent.com/35944271/60390588-ba5bc500-9b0c-11e9-915f-ad1ced22e225.png)
![image](https://user-images.githubusercontent.com/35944271/60390590-ca73a480-9b0c-11e9-9c08-36899c1f0c95.png)
![image](https://user-images.githubusercontent.com/35944271/60390591-d65f6680-9b0c-11e9-8733-8072aab3d9f3.png)

**Comment by pengweiqhca** [comment]
通过输出日志，应该是一个特殊的小问题。你第一次启动，本地没有缓存文件，远程加载也超时了也会出现。

**Comment by cysnet** [comment]
docker quick start 需配置ConfigServer节点
