### ISSUE TITLE
appsettings.json Env不起作用

### ISSUE THREAD

**Issue by cysnet** [ctripcorp/apollo.net#68]
`{
  "Apollo": {
    "AppId": "netcore",
    "MetaServer": "http://10.2.2.139:8080",
    "Env": "Pro",
    "ConfigServer": [ "http://10.2.2.140:8080/" ]
  }
}`

配置如上，但是获取的配置还是DEV的。Env节点不起作用

**Comment by pengweiqhca** [comment]
`Env`是和apollo:Meta:{Env}使用的，具体请看[文档](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#123-服务地址)
