### ISSUE TITLE
请发布Nuget包时别移除之前的版本

### ISSUE THREAD

**Issue by kangduty** [ctripcorp/apollo.net#71]
请发布Nuget包时别移除之前的版本，如果你发的包不稳定，请用alpha版本或者beta版本。不然影响项目开发

**Comment by pengweiqhca** [comment]
没删除，只是隐藏，不影响包还原

**Comment by antspace** [comment]
我这边也找不到我之前使用的1.5.0这个版本了，你们现在的2.0.3这个版本本地开发环境无法读取本地文件config-cache的缓存信息

**Comment by kangduty** [comment]
了解
