### ISSUE TITLE
.net framework appsettings duplicate key error

### ISSUE THREAD

**Issue by akaxb** [ctripcorp/apollo.net#75]
![image](https://user-images.githubusercontent.com/6300834/62277992-d6d77e00-b479-11e9-936b-cb4544a4777b.png)
类似这种配置，现在好像读取会报错，xml解析的时候把"add key"作为键了
![error](https://user-images.githubusercontent.com/6300834/62277958-caebbc00-b479-11e9-9607-a7e2b55c57be.png)

**Comment by pengweiqhca** [comment]
这个行为是遵循官方逻辑https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Xml/src/XmlStreamConfigurationProvider.cs#L91

**Comment by akaxb** [comment]
就是说，类似appSettings这种xml配置，如果我想直接从本地迁移到apollo，现在是不支持的，是吗？还是我的姿势有问题

**Comment by pengweiqhca** [comment]
直接默认namespace配置成key=value，不需要使用xml格式
