### ISSUE TITLE
有包含开放平台操作Apollo服务的请求api吗

### ISSUE THREAD

**Issue by liuyl1992** [ctripcorp/apollo.net#76]
有包含开放平台操作Apollo服务的请求api吗

**Comment by pengweiqhca** [comment]
暂时还没有，Coding

**Comment by pengweiqhca** [comment]
功能已经完成 Com.Ctrip.Framework.Apollo.OpenApi.DependencyInjection

**Comment by liuyl1992** [comment]
效率好快。。赞，不过暂时根据开放平台的http文档开发了操作apollo的sdk
