### ISSUE TITLE
操作超时如何解决？

### ISSUE THREAD

**Issue by songscode** [ctripcorp/apollo.net#82]
提示：`Could not complete get operation [Cause: The operation has timed out ]`
设置Apollo.Timeout，Apollo.ReadTimeout也无法解决。

**Comment by pengweiqhca** [comment]
这个时候建议确定一下网络是否互通，特别是部署在docker中的时候

**Comment by songscode** [comment]
> 
> 
> 这个时候建议确定一下网络是否互通，特别是部署在docker中的时候

开发本地环境，调试成功。部署到测试服务器，提示操作超时。测试服务器能够ping通apollo服务器。
没办法apollo请求中特殊处理：
` req.ServicePoint.Expect100Continue = false;
  req.KeepAlive = true;`

**Comment by nobodyiam** [comment]
看下实际访问的config service ip是不是通。
应用中配置的服务器地址是meta server地址，client会首先从meta server寻找config service的地址，而后再连接实际的config service地址。
