### ISSUE TITLE
使用强类型配置注入的问题

### ISSUE THREAD

**Issue by ZUOXIANGE** [ctripcorp/apollo.net#85]
看多数demo都是直接注入IConfiguration使用的.我想使用强类型的[Options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2),不知道这方面支持怎么样.

单例的`IOptions<TOptions>`是肯定可以的,`IOptionsMonitor<TOptions>`呢?

**Comment by pengweiqhca** [comment]
`IConfiguration`和`IOptions`是两个层面上的事情，使用Configure方法实现绑定.
`services.Configure<TOptions>(configuration)`

**Comment by ZUOXIANGE** [comment]
这个我知道,我上边给的参考链接也是这个...

我的意思是,当我注入`IOptions<TOptions>`的时候,这个是单例的,我在Apollo修改配置的值之后,获取到的配置值肯定是不会改变的.我想使用`IOptionsMonitor<TOptions>`注入解决这个问题,不知道这个SDK会实现相应改变事件的监听改变对应的配置项的值吗?

**Comment by pengweiqhca** [comment]
完全支持的，也可以使用`IOptionsSnapshot<TOptions>`

**Comment by ZUOXIANGE** [comment]
``` csharp

services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptions<>), typeof(OptionsManager<>)));
services.TryAdd(ServiceDescriptor.Scoped(typeof(IOptionsSnapshot<>),typeof(OptionsManager<>)));
services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>)));

```
我想应该是单例的性能会比较好吧.我还停留在看文档写demo阶段╮(╯▽╰)╭Apollo环境还没搭起来,中秋争取搞台机器用起来...
