### ISSUE TITLE
System.MissingMethodException 找不到方法？

### ISSUE THREAD

**Issue by WangJunZzz** [ctripcorp/apollo.net#88]
运行环境：.Net Framework4.7.2
![image](https://user-images.githubusercontent.com/25657426/65017267-e7c04e00-d958-11e9-967e-069eb6e1cae8.png)

**Comment by pengweiqhca** [comment]
不单独更新`Com.Ctrip.Framework.Apollo`或者更新`Com.Ctrip.Framework.Apollo.Configuration`到2.0.4

**Comment by WangJunZzz** [comment]
在Nuget服务器上最新的是2.0.3

**Comment by pengweiqhca** [comment]
> 在Nuget服务器上最新的是2.0.3

刚上传，等几分钟

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/65019951-d0845f00-d95e-11e9-895c-494bda556f7d.png)
被git上的文档说有的晕。

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.AspNet.Demo/Web.config#L3~L13

**Comment by WangJunZzz** [comment]
之前就配置了这个 
![image](https://user-images.githubusercontent.com/25657426/65022411-8782d980-d963-11e9-815a-afe8dde83444.png)
![image](https://user-images.githubusercontent.com/25657426/65022431-98334f80-d963-11e9-9cdf-c12755e37dec.png)

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/65022844-46d79000-d964-11e9-9fb8-c766f83c7557.png)

**Comment by pengweiqhca** [comment]
看这个[框架集成](https://github.com/ctripcorp/apollo.net#一框架集成)

**Comment by WangJunZzz** [comment]
选择的是Com.Ctrip.Framework.Apollo.Configuration，但是程序按照集成框架配置的，都抛异常
![image](https://user-images.githubusercontent.com/25657426/65024753-0843d480-d968-11e9-9853-da52aa4f5a0b.png)

**Comment by pengweiqhca** [comment]
这个需要Com.Ctrip.Framework.Apollo.ConfigurationManager包

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/65025000-74263d00-d968-11e9-9240-4bc210fecff5.png)
三个包我都引用了

**Comment by pengweiqhca** [comment]
检查一下bin目录里是否有Com.Ctrip.Framework.Apollo.ConfigurationManager.dll

**Comment by WangJunZzz** [comment]
好了可以获取了到了， 谢谢！！！ 不过建议.net 的Wiki文档重新写一下，有点乱。
