### ISSUE TITLE
引用Release模式下编译的dll文件在iis应用重启后会导致cpu占用非常高

### ISSUE THREAD

**Issue by cntangt** [ctripcorp/apollo.net#9]
网站部署在IIS上面，引用Release模式下编译的dll文件，如果修改web.config文件，此时应用程序会重启，CPU占用非常高，且不下降，只有通过结束iis进程

通过VS性能跟踪能发现是Newtonsoft.Json的反复调用占用了cpu，使用Debugsaaa模式编译dll不存在这个问题

![image](https://user-images.githubusercontent.com/32816469/35926386-fe542250-0c62-11e8-8b82-79274b3a8cf6.png)

**Comment by nobodyiam** [comment]
这个问题貌似我们没有遇到过，是修改了web.config文件导致iis自动重启的场景出现这个问题？

**Comment by cntangt** [comment]
是的，网站部署在iis上面，每修改一次web.config，CPU就会增加大概40%的占用（i5的处理器）

我现在只有用Debug模式编译的dll

另外我测试了dot-core分支下面的客户端，没有这个问题，但是配置方式好像有了变化，

Evn不能从opt文件夹中读取了，写在web.config中的Apollo.Evn的值有大小写区分，
例如：Apollo.Evn=FAT，就不必，必需是Apollo.Evn=Fat

**Comment by cntangt** [comment]
找到问题了，但是不明白为什么在Debug模式下不会报这个错误

![image](https://user-images.githubusercontent.com/32816469/35951838-29219120-0cb8-11e8-8a02-afc44b02a6a4.png)

首先这个地方有一个后台线程在执行死循环更新配置（因为Tread.IsBackground=true，所以当web站点重启的时候，这个线程因为是死循环，所以没有结束，但是他所使用的对象都已经被释放，此时的RefreshInterval值应该是0，所以线程Thread.Sleep无效，CUP占用就会非常高），根据日志记录信息来看应该也是这样
![image](https://user-images.githubusercontent.com/32816469/35952042-052816da-0cb9-11e8-9009-513d69ef036a.png)

**Comment by nobodyiam** [comment]
@cntangt 

看了下代码还是想确认一下CPU高的原因，因为`m_configUtil.RefreshInterval`是一个常量 - 5分钟，不会是0的，所以不会产生死循环。

我猜测是否是因为线程没有catch `ThreadInterruptedException`或`ThreadAbortException`，导致线程一直无法停止，然后一直在尝试停止线程，导致CPU高？

是否可以帮忙在原有代码中的catch Exception后，把Exception打印出来看看？

另外，也可以尝试catch到类似这种线程中断的异常后就跳出while循环是否也能解决这个问题？

**Comment by shenshuan** [comment]
我也碰到了这个问题，采用0.1.0版本IIS进程cpu占用飙升。
进行debug发现，更改配置后此处异常，但在debug只报错一次。
![image](https://user-images.githubusercontent.com/21232965/37269542-cb6a82f0-2605-11e8-8ea1-c5dc72f6020d.png)
![image](https://user-images.githubusercontent.com/21232965/37269577-f0192b9c-2605-11e8-822c-7bcce956cc14.png)
在release下死循环
![image](https://user-images.githubusercontent.com/21232965/37272573-fb41d814-2611-11e8-9cc0-a8496c1bb2c3.png)
