### ISSUE TITLE
.net core 客户端能否把日志加上呢？没有日志太不方便了

### ISSUE THREAD

**Issue by zpc870921** [ctripcorp/apollo.net#91]
.net core 客户端能否把日志加上呢？没有日志太不方便了

**Comment by pengweiqhca** [comment]
> 默认Sdk内部的日志不会输出，需要输出日志的请设置Com.Ctrip.Framework.Apollo.Logging.LogManager.LogFactory属性。

输出控制台日志
``` C#
LogManager.UseConsoleLogging(LogLevel.Trace);
```

**Comment by zpc870921** [comment]
@pengweiqhca   好的，多谢了，正在研究源码，感谢提供这么好的工具
