### ISSUE TITLE
使用内存过高

### ISSUE THREAD

**Issue by Yeshuaihui** [ctripcorp/apollo.net#93]
手里有一个.net core api的项目，情况是这样的：
在没有使用阿波罗配置的时候 这个项目占用的内存基本是在50M左右的，一旦启用了阿波罗配置，并且访问之后每次访问差不多都能增加1M左右的内存使用而没有使用阿波罗则没有这种情况

**Comment by pengweiqhca** [comment]
你可以将dump给我，我帮你分析一下

**Comment by Yeshuaihui** [comment]
大佬  我在微软上没下载下来 你有dump的包嘛

**Comment by Yeshuaihui** [comment]
文件太大了  压缩后71M
传不上去

**Comment by pengweiqhca** [comment]
发我邮箱pengwei@tuhu.cn

**Comment by Yeshuaihui** [comment]
我貌似找到原因了，同事对你们的客户端代码进行了封装，每次调用配置的时候都走了一遍`                var builder = AddJsonConfig();
                IConfiguration apolloConfiguration = builder.Build().GetSection("apollo");
                try
                {
                    IApolloConfigurationBuilder apolloBuilder = builder.AddApollo(apolloConfiguration);//注意：如果配置文件中没有添加apollo的配置，这里会异常
                    if (string.IsNullOrEmpty(namespaceName))
                    {
                        apolloBuilder.AddDefault();
                    }
                    else
                    {
                        apolloBuilder.AddNamespace(namespaceName);
                    }
                    config= builder.Build();
                }
                catch (Exception ex)
                {
                    config= builder.Build();
                }`
我猜想很有可能是每次都是创建了一个新的客户端与服务器的链接了导致的
我给他改了一下 加了一个静态字典存储起来以namespace为key下次要使用的话直接从字典里面获取
昨天测了一下内存情况是没有了，等下测试下配置修改了的话客户端能否拿到最新的配置

**Comment by Yeshuaihui** [comment]
我按照我的思路测试了一下 阿波罗的功能都是正常的，的确是我同事代码有问题 已经改过来了
