### ISSUE TITLE
ConfigService 挂了，重启配置不能同步问题

### ISSUE THREAD

**Issue by nixiaodong** [ctripcorp/apollo.net#96]
场景：在使用apollo.net 客户端的时候，如ConfigService 挂了，在这期间使用portal发布新的配置（提示发布成功，实例列表会提示应用使用非最新的配置），重新启用ConfigService,等待服务正常，但是客户端拉取后依旧没有更新到最新的配置，但是portal 实例列表提示以及使用最新的配置了；
问题所在：客户端在执行拉取任务中，在执行GetConfig（）时，会先判断_syncException，如果有异常就会直接抛出，如下图：
![image](https://user-images.githubusercontent.com/24214938/67916385-7ff45880-fbd0-11e9-9903-8c99e9d52e2c.png)

所以在ConfigService 挂掉，再重新启动这个_syncException 异常没有及时的清除，查找了一下，看到（如下图）
![image](https://user-images.githubusercontent.com/24214938/67916370-7539c380-fbd0-11e9-9e0c-065f7cad7f3e.png)
这里在同步配置的时候没有及时的清除_syncException，导致更新不了
结果：我尝试及时的清除_syncException，表现正常，希望能尽快解决整个问题（不知道java客户端是否也有整个问题）；

**Comment by pengweiqhca** [comment]
你可以提交一个pr

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/pull/97 已修复，包将晚几天发布

**Comment by nixiaodong** [comment]
ok  感谢

**Comment by nixiaodong** [comment]
> #97 已修复，包将晚几天发布
ok  感谢
