### ISSUE TITLE
使用仓库中提供的ASP.NET Core程序，链接docker下部署的apollo服务获取值为null

### ISSUE THREAD

**Issue by Myosotissylvatica36** [ctripcorp/apollo.net#99]

**Comment by pengweiqhca** [comment]
https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-如何跳过meta-service的服务发现

**Comment by Myosotissylvatica36** [comment]
> [https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-如何跳过meta-service的服务发现](https://github.com/ctripcorp/apollo.net/blob/dotnet-core/Apollo.Configuration/README.md#43-%E5%A6%82%E4%BD%95%E8%B7%B3%E8%BF%87meta-service%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0)

感谢您的回复。
